config/routes.rb
Planner::Application.routes.draw do

  scope :module => 'api' do

  end

  root :to => 'sessions#welcome'

  match "/signout"      => "sessions#destroy", :as => :signout

  get '/budget'         => 'budget#index',    :as => 'budget'
  get   '/manage'       => 'manage#index',    :as => 'manage'
  post  '/manage'       => 'manage#create',   :as => 'create_category'
  put  '/manage/:id'    => 'manage#update',   :as => 'update_category'
  get '/manage/:id'     => 'manage#edit',     :as => 'category'
  delete '/manage/:id'  => 'manage#delete',   :as => 'delete_category'

  get '/plan'           => 'plan#index',      :as => 'plan_index'
  get '/plan/new'       => 'plan#new',        :as => 'new_activity'
  post '/plan'          => 'plan#create',     :as => 'create_activity'
  put '/plan/:id'       => 'plan#update',     :as => 'update_activity'
  get '/plan/:id/edit'  => 'plan#edit',       :as => 'edit_activity'
  delete 'plan/:id'     => 'plan#delete',     :as => 'activity'

  resources :users

  resources :sessions do
    collection do
      post 'login', :action => 'create'
    end
  end

  match "/auth/:provider/callback" => "sessions#create"

end

app/controllers/budget_controller.rb
require 'active_support/all'
class BudgetController < ApplicationController

  before_filter :events
  helper_method :time_by_activity, :day_name

  def index
    @this_week = events.where({time_min: beginning_of_week,
                                          time_max: beginning_of_week + 7.days})

    @last_week = events.where({time_min: beginning_of_week - 7.days,
                                              time_max: beginning_of_week})

    @categories = current_user.categories.includes(:activities).all
  end

  def time_by_activity(event_set, old_activity_id, i = nil)
    selected_events = event_set.select do |event|
      correct_activity_id = event[:old_activity_id] === old_activity_id
      correct_day = i ? event[:start].wday === i : true

      correct_activity_id && correct_day
    end

    selected_events.map { |e| e[:time] }.reduce(:+)
  end

  def day_name(i)
    (beginning_of_week + i.days).strftime('%a')
  end
end

app/views/budget/index.html.erb
<p id="notice"><%= notice %></p>

<div class="heading">
  <div class="row">
    <div class="large-2 columns">&nbsp;</div>
    <% (0..6).each do |i| %>
      <div class="large-1 columns">
        <%= day_name(i) %>
      </div>
    <% end %>
    <div class="columns large-1">Total</div>
    <div class="columns large-1">Last Week</div>
  </div>
</div>
<% @categories.each do |category| %>

  <div class="row category">
    <% category.activities.each do |activity| %>
      <%# next unless activity.budget && activity.budget > 0 %>
      <div class="row activity-row">
        <div class="row-12 columns activity-summary" data-activity-id='<%= activity.id %>'>
          <div class="large-2 columns">
            <%= link_to(edit_activity_path(activity)) do %>
              <%= activity.name %>
            <% end %>
          </div>
          <% (0..6).each do |i| %>
            <div class="large-1 columns">
              <%= time_by_activity(@this_week, activity.old_id, i) %>
            </div>
          <% end %>
          <div class="large-1 columns">
            <%= time_by_activity(@this_week, activity.old_id) %>
          </div>
          <div class="large-1 columns">
            <%= time_by_activity(@last_week, activity.old_id) %>
          </div>
        </div>
      </div>

    <% end %>
    <div class="row">
      <div class="row-12 columns category-total">
        <div class="large-4 columns">
          <%= link_to(category_path(category)) do %>
            Total <%#= category.name %>
          <% end %>
        </div>
        <div class="large-8 columns">
          <% [0..6].each do |i| %>
            <%#= event_day_category_total(category, i) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>