config/routes.rb
Planner::Application.routes.draw do

  scope :module => 'api' do

  end

  root :to => 'sessions#welcome'

  match "/signout"      => "sessions#destroy", :as => :signout

  get '/budget'         => 'budget#index',    :as => 'budget'
  get   '/manage'       => 'manage#index',    :as => 'manage'
  post  '/manage'       => 'manage#create',   :as => 'create_category'
  put  '/manage/:id'    => 'manage#update',   :as => 'update_category'
  get '/manage/:id'     => 'manage#edit',     :as => 'category'
  delete '/manage/:id'  => 'manage#delete',   :as => 'delete_category'

  get '/plan'           => 'plan#index',      :as => 'plan_index'
  get '/plan/new'       => 'plan#new',        :as => 'new_activity'
  post '/plan'          => 'plan#create',     :as => 'create_activity'
  put '/plan/:id'       => 'plan#update',     :as => 'update_activity'
  get '/plan/:id/edit'  => 'plan#edit',       :as => 'edit_activity'
  delete 'plan/:id'     => 'plan#delete',     :as => 'activity'

  resources :users

  resources :sessions do
    collection do
      post 'login', :action => 'create'
    end
  end

  match "/auth/:provider/callback" => "sessions#create"

end

app/controllers/plan_controller.rb
class PlanController < ApplicationController

  before_filter :require_current_user

  # GET /activities
  # GET /activities.json
  def index
    @activities = current_user.activities.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = current_user.activities.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = current_user.activities.new
    @categories = current_user.categories

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
    @categories = current_user.categories

    respond_to do |format|
      format.html
      format.json { render json: render_to_string('_mini_form', layout: false, formats: [:html]) }
    end

  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = current_user.activities.create!(params[:activity])
    redirect_to plan_index_path, notice: 'Activity was successfully created.'
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = current_user.activities.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.json { render json: {activity: render_to_string('_mini_activity', layout: false, formats: [:html], locals: {activity: @activity})} }
        format.html { redirect_to plan_index_path, notice: 'Activity was successfully updated.' }
      else
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def delete
    @activity = current_user.activities.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to manage_url }
      format.json { head :no_content }
    end
  end

  private

  def require_current_user
    unless current_user
      head :forbidden
    end
  end
end

app/views/plan/_form.html.erb
<%= form_for(@activity,url:activity_path(@activity.id)) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% @activity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <fieldset>
    <legend>Activity</legend>

    <div class="row">
      <div class="large-12 columns">
        <div class="large-3 columns">
          <label>Activity Name</label>
          <%= f.text_field :name, placeholder: "Choose a Name" %>
        </div>
        <div class="large-2 columns">
          <label>Hours per Week</label>
          <%= f.number_field :budget, placeholder: "Hours per Week" %>
        </div>
        <div class="large-2 columns">
          <label>Google Code</label>
          <%= f.number_field :old_id %>
        </div>
        <div class="large-3 columns end">
          <label>Category</label>
          <%= f.select :category_id, @categories.map { |category| [category.name, category.id] }, selected: @activity.category_id, placeholder: "large-3.columns" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="large-3 columns">
        <div class="actions">
          <%= f.submit class: "button round" %>
        </div>
      </div>
    </div>
  </fieldset>

<% end %>

app/views/plan/_mini_activity.html.erb
<div class="row-12 columns activity" data-activity-id="<%= activity.id %>" data-category-id="<%= activity.category.id %>">
  <div class="large-4 large-offset-1 columns"><%= activity.name %></div>
  <div class="large-1 columns"><%= activity.budget || "--" %></div>
  <div class="large-1 columns"><%= activity.old_id %></div>
  <div class="large-1 columns"><i class='icon-pencil edit-activity'></i></div>
  <div class="large-1 columns end">
    <%= link_to "<i class='icon-remove'></i>".html_safe, activity, method: :delete, data: {confirm: 'Delete activity?'} %>
  </div>
</div>

app/views/plan/_mini_form.erb
<div class="large-12 columns activity-form">
  <%= form_for(@activity, remote: true, html: {'data-type' => 'json'}) do |f| %>

    <div class="large-4 large-offset-1 columns">
      <%= f.text_field :name, placeholder: "New Activity Name" %>
    </div>
    <div class="large-1 columns">
      <%= f.number_field :budget, placeholder: "Hours per Week" %>
    </div>
    <div class="large-1 columns">
      <%= f.number_field :old_id %>
    </div>
    <div class="large-1 columns end">
      <i class="icon-ok form-submit"></i>
    </div>
    <%= f.hidden_field :category_id %>

  <% end %>
</div>

app/views/plan/edit.html.erb
<h1>Edit an activity</h1>

<%= render 'form' %>

app/views/plan/index.html.erb
<table>
<% @activities.each do |activity| %>
    <tr>
      <td><%= activity.old_id %></td>
      <td><%= activity.name %></td>
    <td><%= activity.category_id %></td>
    <td><%= activity.budget %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%#= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/plan/new.html.erb
<h1>Create a new activity</h1>

<%= form_for(@activity, url: create_activity_path, method: :post) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% @activity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <fieldset>
    <legend>Activity</legend>

    <div class="row">
      <div class="large-12 columns">
        <div class="large-3 columns">
          <label>Activity Name</label>
          <%= f.text_field :name, placeholder: "Choose a Name" %>
        </div>
        <div class="large-2 columns">
          <label>Hours per Week</label>
          <%= f.number_field :budget, placeholder: "Hours per Week" %>
        </div>
        <div class="large-2 columns">
          <label>Google Code</label>
          <%= f.number_field :old_id %>
        </div>
        <div class="large-3 columns end">
          <label>Category</label>
          <%= f.select :category_id, @categories.map { |category| [category.name, category.id] }, selected: @activity.category_id, placeholder: "large-3.columns" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="large-3 columns">
        <div class="actions">
          <%= f.submit class: "button round" %>
        </div>
      </div>
    </div>
  </fieldset>

<% end %>

app/views/plan/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @activity.name %>
</p>

<p>
  <b>Repeating:</b>
  <%= @activity.repeating %>
</p>

<p>
  <b>Category:</b>
  <%= @activity.category_id %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |