config/routes.rb
Planner::Application.routes.draw do

  scope :module => 'api' do

  end

  root :to => 'sessions#welcome'

  match "/signout"      => "sessions#destroy", :as => :signout

  get '/budget'         => 'budget#index',    :as => 'budget'
  get   '/manage'       => 'manage#index',    :as => 'manage'
  post  '/manage'       => 'manage#create',   :as => 'create_category'
  put  '/manage/:id'    => 'manage#update',   :as => 'update_category'
  get '/manage/:id'     => 'manage#edit',     :as => 'category'
  delete '/manage/:id'  => 'manage#delete',   :as => 'delete_category'

  get '/plan'           => 'plan#index',      :as => 'plan_index'
  get '/plan/new'       => 'plan#new',        :as => 'new_activity'
  post '/plan'          => 'plan#create',     :as => 'create_activity'
  put '/plan/:id'       => 'plan#update',     :as => 'update_activity'
  get '/plan/:id/edit'  => 'plan#edit',       :as => 'edit_activity'
  delete 'plan/:id'     => 'plan#delete',     :as => 'activity'

  resources :users

  resources :sessions do
    collection do
      post 'login', :action => 'create'
    end
  end

  match "/auth/:provider/callback" => "sessions#create"

end

app/views/layouts/_top_bar.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name"><img class="main-logo" src="/images/orange.png" ></li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Budget", budget_url %></li>
      <li class="divider"></li>
      <li><%= link_to "Plan", plan_index_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Manage", manage_url %></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planner</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/top_bar' %>
  <%= yield %>

</body>
</html>